[pytest]
testpaths = tests
pythonpath = .
python_files = test_*.py
python_classes = Test*
python_functions = test_*
markers =
    integration: Slow integration tests
addopts =
    --verbose
    --cov=app
    --cov=scripts
    --cov-report=term-missing
    --cov-report=html
